sudo: false
language: python
python:
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements-dev.txt
script:
  - pre-commit run -a --show-diff-on-failure
  - py.test
